global:
  scrape_interval: 5s
  external_labels:
    monitor: "app-api-say"
scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["prometheus.srv.com:9090"]
  - job_name: "node-exporter"
    static_configs:
      - targets: ["prometheus.srv.com:9090"]
  - job_name: "app-api-say"
    scrape_interval: 5s
    static_configs:
      - targets: ["app.api.say.com:9080"]